FROM alpine:3.7

RUN apk add --no-cache bash vim alpine-sdk cmake

ADD . /build
WORKDIR /build

RUN cmake .
RUN make

RUN gcc test/oom/leak.c -o leak

CMD ["./tini", "-v", "-v", "-v", "-m", "./leak"]
